libapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("view_book/<int:isbn>/", views.view_book, name="view_book"),
    path("categories/", views.categories, name="categories"),
    path("view_category/<str:name>/", views.view_category, name="view_category"),
    path("request_book/<str:isbn>/", views.request_book, name="request_book"),
    path("login/", views.student_login, name="student_login"),
    path("register/", views.student_registration, name="student_registration"),
    path("profile/", views.student_profile, name="student_profile"),
    path("notifications/<int:idnumber>/", views.notifications, name="notifications"),
    path("view_my_books/<int:idnumber>/", views.view_my_books, name="view_my_books"),
    path("request_book/<str:isbn>/", views.request_book, name="request_book"),
    path("return_book/<str:isbn>/", views.return_book, name="return_book"),
    path("search/", views.search_book, name="search_book"),
    path("logout/", views.logoutuser, name="logoutuser"),
]

ubuntulibrary/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("libapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime,timedelta

# Create your models here.
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    isbn = models.PositiveIntegerField()
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to="book-images")

    def __str__(self):
        return str(self.name) + " ["+str(self.isbn)+']'

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True)
    course = models.CharField(max_length=10)
    id_nnumber = models.CharField(max_length=3, blank=True)
    phone = models.CharField(max_length=10, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " ["+str(self.course)+']' + " ["+str(self.id_nnumber)+']' + " ["+str(self.phone)+']'

class Category(models.Model):
    title = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title


def expiry():
    return datetime.today() + timedelta(days=7)

class IssuedBook(models.Model):
    student_id = models.CharField(max_length=100, blank=True) 
    bookname = models.CharField(max_length=200, null=True)
    isbn = models.PositiveIntegerField()
    issued_date = models.DateField(auto_now=True)
    expiry_date = models.DateField(default=expiry)

class Notification(models.Model):
    message = models.TextField()
    student_id = models.CharField(max_length=3, blank=True)

libapp/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render,HttpResponse
from datetime import date

# Create your views here.
def index(request):
    books = Book.objects.all()
    return render(request, "home.html", {'books':books})

def view_book(request, isbn):
    bookdetails = Book.objects.get(isbn=isbn)
    return render(request, "view_book.html", {'bookdetails':bookdetails})

def categories(request):
    categories = Category.objects.all()
    return render(request, "categories.html", {'categories':categories})

def view_category(request, name):
    category_books = Book.objects.filter(category=name)
    return render(request, "view_category.html", {'category_books':category_books,'title':name})

@login_required(login_url = '/login')
def request_book(request, isbn):
    issued_book = Issuedbook.objects.filter(isbn=isbn)
    if issued_book != "":
        message 
    else:
        obj = models.IssuedBook()
        obj.student_id = request.user.id
        obj.isbn = isbn
        obj.save()

    return render(request, "request_book.html", {'message'})

@login_required(login_url = '/login')
def student_profile(request):
    return render(request, "profile.html")

def student_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            if request.user.is_superuser:
                return HttpResponse("You are not a student!!")
            else:
                return redirect("/")
        else:
            alert = True
            return render(request, "login.html", {'alert':alert})
    return render(request, "login.html")

def student_registration(request):
    if request.method == "POST":
        username = request.POST['username']
        fullname = request.POST['full_name']
        email = request.POST['email']
        phone = request.POST['phone']
        course = request.POST['course']
        password = request.POST['password']
        idnumber = request.POST['idnumber']

        user = User.objects.create_user(username=username, email=email, password=password)
        student = Student.objects.create(user=user, full_name=fullname, course=course, id_nnumber=idnumber, phone=phone)
        user.save()
        student.save()
        alert = True
        return render(request, "register.html", {'alert':alert})
    return render(request, "register.html")

def notifications(request, idnumber):
    notifications = Notification.objects.filter(student_id=idnumber)
    return render(request, "notifications.html", {'notifications':notifications})

def view_my_books(request, idnumber): 
    issuedBooks = IssuedBook.objects.filter(student_id=idnumber)

    bookdetails = []
    for i in issuedBooks:
        days = (i.expiry_date-i.issued_date)
        d=days.days
        fine=0
        if d<=-3:
            fine=5000
        elif d<=-15:
            fine=15000
        books = list(Book.objects.filter(isbn=i.isbn))
        students = list(Student.objects.filter(id_nnumber=i.student_id))
        i=0
        for l in books:
            t=(students[i].user,students[i].user_id,books[i].name,books[i].isbn,issuedBooks[0].issued_date,issuedBooks[0].expiry_date,fine,d)
            i=i+1
            bookdetails.append(t)

    return render(request, "view_my_books.html", {'issuedBooks':issuedBooks, 'bookdetails':bookdetails})

def request_book(request, isbn):
    checkbook = IssuedBook.objects.filter(isbn=isbn)
    bookdetails = Book.objects.get(isbn=isbn)
    if checkbook.exists():
        msg = "Sorry, This book is not available at the moment"
        return render(request, "request_book.html", {'msg':msg})
    else:
        obj = IssuedBook.objects.create(student_id=request.user.student.id_nnumber, bookname=bookdetails.name, isbn=isbn)
        obj.save()
        msg = "You have booked this book successfully."
        return render(request, "request_book.html", {'msg':msg})

def return_book(request, isbn):
    checkbook = IssuedBook.objects.filter(isbn=isbn)
    if checkbook.exists():
        checkbook.delete()
        msg = "You returned the book."
        return render(request, "return_book.html", {'msg':msg})
    else:
        msg = "Sorry, an error occurred. You probably haven't requested for this book."
        return render(request, "return_book.html", {'msg':msg})

def search_book(request):
    searchvalue = request.GET.get("keyword")
    results = Book.objects.filter(name__icontains=searchvalue)
    return render(request, "search.html", {'results':results})

def logoutuser(request):
    logout(request)
    return redirect ("index")

libapp/templates/basic.html
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ubuntu Library</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="/">UBUNTU LIBRARY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/categories">Categories</a>
            </li>
            {% if request.user.student %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Student
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    
                    <a class="dropdown-item" href="/notifications/{{user.student.id_nnumber}}">Notifications</a>
                    <a class="dropdown-item" href="/view_my_books/{{user.student.id_nnumber}}">Issued Books</a>
                    <a class="dropdown-item" href="/profile">Profile</a>
                    <a class="dropdown-item" href="/logout">Logout</a>
                    
                    </div>
                </li>
            {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                
                <a class="dropdown-item" href="/register">Register</a>
                <a class="dropdown-item" href="/login">Login</a>
                
                </div>
            </li>
            {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0" action="/search/" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>

    {% block content %}

        This content will be replaced by different html code for each page.

    {% endblock %}
    
    {% block js %}
    {% endblock %}
    <script src="{% static 'bootstrap/assets/js/vendor/jquery-slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

libapp/templates/categories.html
{% extends 'basic.html' %}

{% block content %}
<style type="text/css">
    h4{
        font-size:18px;
    }
</style>

<div class="container">
    <h3>All Book Categories</h3><hr>

    {% for category in categories %}
    <h4><a href="/view_category/{{category.title}}">{{category.title}}</a></h4><hr>
    {% endfor %}
    
</div>
{% endblock %}

libapp/templates/home.html
{% extends 'basic.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<div class="container">

    <h1 class="text-center">WELCOME TO UBUNTU ONLINE LIBRARY 
       <P>You can now borrow books at affordable prices </P>

    </h1>
    <hr>
    <div class="row mt-3">
        {% for book in books %}
        <div class="col-md-3 card">
                <div class="m-4">
                    <img src="{{book.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                    <a class="book-title"  href="/view_book/{{book.isbn}}/">{{book.name}}</a>
                    <span class="book-author">{{book.author}}</span>
                    {% if request.user.student %}
                    <a href="/request_book/{{book.isbn}}/" class="btn btn-primary">Book Now</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

libapp/templates/login.html
{% extends 'basic.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Student Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                <p><label for="id_username">Username:</label> <input type="text" name="username" required id="id_username"></p>
<p><label for="id_password">Password:</label> <input type="password" name="password" required id="id_password"></p>
                <button class="btn btn-primary">Login as Student</button>
                
            </form>
            <p> or don't have account? <a href="/register">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    {% if alert %}
    alert("Invalid Username or Password.")
    document.location = "/login"
    {% endif %}
</script>
{% endblock %}

libapp/templates/notifications.html
{% extends 'basic.html' %}


{% block content %}
<style type="text/css">
    .notif-card{

    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Notifications</h3>
            <hr>
            {% if notifications.exists %}
                {% for notification in notifications %}
                <div class="notif-card">{{notification.message}}</div>
                {% endfor %}
            {% else %}
                <div class="msg">No notifications for you.</div>
            {%  endif %}
        </div>
    </div>
</div>
{% endblock %}

libapp/templates/profile.html
{% extends 'basic.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{user.student.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{user}}</p>
            <p><span class="font-weight-bold">Email: </span> {{user.email}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{user.student.joined_on}}</p>
        </div>
    </div>
</div>
{% endblock %}

libapp/templates/register.html
{% extends 'basic.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Student Registration Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                <p><label for="username">Username:</label> <input type="text" name="username" maxlength="200" required id="username"></p>
                <p><label for="id_full_name">Full name:</label> <input type="text" name="full_name" maxlength="200" required id="id_full_name"></p>
                <p><label for="id_email">Email:</label> <input type="email" name="email" required id="id_email"></p>
<p><label for="id_password">Password:</label> <input type="password" name="password" required id="id_password"></p>
<p><label for="id_address">Course:</label> <input type="text" name="course" maxlength="200" id="id_course"></p>
<p><label for="id_idnumber">ID No.:</label> <input type="text" name="idnumber" maxlength="3" id="id_idnumber"></p>
<p><label for="id_phone">Phone:</label> <input type="text" name="phone" maxlength="200" id="id_phone"></p>
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            <p> Already have an account? <a href="/login/">Login here</a></p>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    {% if alert %}
    alert("Registration Successfull.")
    document.location = "/login"
    {% endif %}
</script>
{% endblock %}

libapp/templates/request_book.html
{% extends 'basic.html' %}


{% block content %}
    
    <h4 style="margin-left:20px;">{{ msg }}</h4>

{% endblock %}

libapp/templates/return_book.html
{% extends 'basic.html' %}


{% block content %}

    <p style="margin-left:20px;">
        <h4>{{ msg }}</h4>
        <p></p>
        <a href="/view_my_books/{{user.student.id_nnumber}}/" class="btn btn-primary">Go back</a>
    </p>

{% endblock %}

libapp/templates/search.html
{% extends 'basic.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row card" style="margin:20px; padding:10px;">
                <div class="col-md-5">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="">{{result.name}}</a></h4>
                    <p>Category: {{result.category}}</p>
                    <p>ISBN: {{result.isbn}}</p>
                    {% if request.user.student %}
                    <a href="/request_book/{{result.isbn}}/" class="btn btn-info">Book Now</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

libapp/templates/student_navbar.html
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ubuntu Library</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="/profile">UBUNTU LIBRARY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/profile">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/categories">Categories</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                
                <a class="dropdown-item" href="/notifications">Notifications</a>
                <a class="dropdown-item" href="/issued_books">Issued Books</a>
                <a class="dropdown-item" href="/profile">Profile</a>
                <a class="dropdown-item" href="/logout">Logout</a>
                
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="/search/" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>

    {% block content %}

        This content will be replaced by different html code for each page.

    {% endblock %}
    
    {% block js %}
    {% endblock %}
    <script src="{% static 'bootstrap/assets/js/vendor/jquery-slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

libapp/templates/view_book.html
{% extends 'basic.html' %}

{% block content %}
<div class="container">
    <h3>Book Name: <b>{{bookdetails.name}}</b></h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{bookdetails.image.url}}" alt="" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h4>{{bookdetails.name}}</h4>
            <p></p>
            <h5>Category: {{bookdetails.category}}</h5>
            <p></p>
            <h5>ISBN: {{bookdetails.isbn}}</h5>
            <p></p>
            {% if request.user.student %}
            <a href="/request_book/{{bookdetails.isbn}}/" class="btn btn-info">Book Now</a>
            {% endif %}
            <hr>
        </div>
    </div>

</div>
{% endblock %}

libapp/templates/view_category.html
{% extends 'basic.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<div class="container">

    <h1 class="text-left">{{title}} Books</h1>
    <hr>
    <div class="row mt-3">
        {% for book in category_books %}
        <div class="col-md-3 card">
                <div class="m-4">
                    <img src="{{book.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                    <a class="book-title"  href="/view_book/{{book.isbn}}/">{{book.name}}</a>
                    <span class="book-author">{{book.author}}</span>
                    {% if request.user.student %}
                    <a href="/request_book/{{book.isbn}}/" class="btn btn-primary">Book Now</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

libapp/templates/view_my_books.html
{% extends 'basic.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>My Issued Books</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>Count</th>
                        <th>Book Title</th>
                        <th>Book ISBN</th>
                        <th>Ordered on</th>
                        <th>Return Date</th>
                        <th>Remaining Days</th>
                        <th>Fine</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in bookdetails %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{i.2}}</td>
                        <td>{{i.3}}</td>
                        <td>{{i.4}}</td>
                        <td>{{i.5}}</td>
                        <td>{{i.7}}</td>
                        <td>Shs. {{i.6}}</td>
                        <td><a href="/return_book/{{i.3}}" class="btn btn-primary">Return</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}